id: P004258
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09736
  title: ས་སྐྱ་ཆོས་འབྱུང་
  author: ''
  volumes:
    a20efd50b0024c15b0d54db111ee9de3:
      image_group_id: I00KG09782
      title: ''
      volume_number: 1
      total_pages: 96
