id: P004258
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG09736
  title: ས་སྐྱ་ཆོས་འབྱུང་
  author: ''
  volumes:
    a20efd50b0024c15b0d54db111ee9de3:
      image_group_id: I00KG09782
      title: ''
      volume_number: 1
      total_pages: 96
      base_file: v001.txt
