id: I7041918B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:59:47+00:00'
last_modified: '2022-06-07T21:28:36.212937+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09736
  title: ས་སྐྱ་ཆོས་འབྱུང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E699:
      image_group_id: I00KG09782
      title: ''
      total_pages: 96
      order: 1
      base_file: E699.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
